[package]
name = "opn"
version = "0.4.0"
edition = "2021"
license = "MIT"

[dependencies]

[profile.release]
# optimize for binary size
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
